#!/bin/bash

cd $HOME/Documents/Website/
#examples of NAME include may1st or september19th
#will later be appened to .html

NAME=$1
#creates html file of command line arg NAME
> "$NAME.html"

#stores a barebones html document used for all my blogs as this new html file
cat blogtemp.html >> "$NAME.html"

#open with sublime
sublime "$NAME.html"
