#!/bin/bash
# crypten - a script to encrypt files using openssl

FILE=$1

if [ $FILE == -h ]; then
    echo "crypten <name of file>";
    echo "  - crypten is a script to encrypt files using des3";
    exit;
fi

openssl des3 -salt -in "$FILE" -out "$FILE.des3"
