#!bin/bash
exec > $HOME/tmp/output.html


cd /users/tutors/mhtest15/share/shakespeare/


echo '<pre>'
grep -i "$1"  */*html |    sed -e 's|<|\&lt;|g'   |   sed -e 's|>|\&gt;|g' | clickable
echo '</pre>'
