#!/bin/bash

FILE=$1

DIR=$HOME/Documents/JS30/

if [ -e "$FILE.html" ]; then
        sshpass -p 'exhem96w' scp -r $FILE.html mcdermj7@student.computing.dcu.ie:~/public_html/JS30
        echo $FILE.html has been pushed!
        exit 0
fi

if [ -e "$FILE.css" ]; then
        sshpass -p 'exhem96w' scp -r $FILE.css mcdermj7@student.computing.dcu.ie:~/public_html/JS30
        echo $FILE.css has been pushed!
        exit 0
fi


if [ -e "$FILE.js" ]; then
        sshpass -p 'exhem96w' scp -r $FILE.js mcdermj7@student.computing.dcu.ie:~/public_html/JS30
        echo $FILE.js has been pushed!
        exit 0
fi
