#!/bin/bash

#updates my cv on my website

cd $HOME/Google\ Drive/
#google drive is where my cv is found

if [ -e "mycv.pdf" ]; then
	sshpass -p 'password' scp -r mycv.pdf user@host/public_html
	# safely copies it to where I host my site
	
	D=$(date +"%D")
	T=$(date +"%T")
  	#set date and time of update
	
	echo "CV updated at $T on $D"
  	#echoes update
fi
