#!/usr/bin/env bash

# I use this to gather brickbot command invocations using journalctl.
# Check out brickbot here --> https://github.com/theycallmemac/brickbot
# I run this script every minute with a cronjob
# Data scraped from this script is stored in a yaml file.

main() {
    touch /tmp/stats.yaml
    rm /tmp/stats.yaml
    commands=("bus" "coinflip" "isitup" "luas" "nslookup" "pwgen" "pwned" "room" "ssl" "weather" "wiki" "uptime")
    for cmd in "${commands[@]}"; do
        get_invocation_count
        echo "$cmd: $count" >> /tmp/stats.yaml
    done;
    get_diff
    if [[ ($? != 0) && ($count != 0) ]]; then
        mv /tmp/stats.yaml /tmp/brickbot.stats.yaml
    fi
    return 0
}

get_invocation_count() {
    count=$(journalctl -u brickbot | grep Command | grep $cmd | wc -l)
}

get_diff() {
    diff /tmp/stats.yaml /tmp/brickbot.stats.yaml > /tmp/brickbot.diffs
}

main || exit 1
exit 0
